//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AnotherRealisation.h
//  @ Date : 28/03/2022
//  @ Author : smr
//
//


#if !defined(_ANOTHERREALISATION_H)
#define _ANOTHERREALISATION_H

#include "myAbstract.h"

class AnotherRealisation : public myAbstract {
public:
	void bang();
};

#endif  //_ANOTHERREALISATION_H
