//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AnotherRealisation.cpp
//  @ Date : 28/03/2022
//  @ Author : smr
//
//


#include "AnotherRealisation.h"

void AnotherRealisation::bang() {

}

