//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Arealisation.cpp
//  @ Date : 28/03/2022
//  @ Author : smr
//
//


#include "Arealisation.h"

void Arealisation::bang() {

}

