//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Arealisation.h
//  @ Date : 28/03/2022
//  @ Author : smr
//
//


#if !defined(_AREALISATION_H)
#define _AREALISATION_H

#include "myAbstract.h"

class Arealisation : public myAbstract {
public:
	void bang();
};

#endif  //_AREALISATION_H
