//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : myAbstract.h
//  @ Date : 28/03/2022
//  @ Author : smr
//
//


#if !defined(_MYABSTRACT_H)
#define _MYABSTRACT_H


class myAbstract {
public:
	virtual void bang() = 0;
};

#endif  //_MYABSTRACT_H
