//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : A.cpp
//  @ Date : 17/03/2022
//  @ Author : smr
//
//


#include "A.h"

void A::get() {

}

void A::set() {

}

bool A::validate() {

}

