//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : B.cpp
//  @ Date : 17/03/2022
//  @ Author : smr
//
//


#include "B.h"

B::B() {

}

B::~B() {

}

int B::getD() {

}

void B::setD(int i) {  // default argument = 0 removed manually

}

void B::setName(char* nam) {

}

const char* B::getAddress() {

}

bool B::validate() {

}

B& B::operator++() {

}

B& B::operator+(const B& r) {

}

ostream & operator<<(ostream &os, const B& bb) {  // as it is a friend not a member, membership of B:: is removed manually

}

