Lab 4: classes/REGIST.CPP File Reference
REGIST.CPP File Reference
#include "REGIST.H"
Functions
istream & operator>> (istream &input, Registration &R)
Operator overload for input.
ostream & operator<< (ostream &os, Registration &R)
Operator overload for output.
Function Documentation
operator<<()
ostream& operator<< (ostream & os, Registration & R)
Operator overload for output.
Parameters
os is the output stream
R is the object for Registration
Definition at line 85 of file REGIST.CPP.
 {
   os << "Student ID: " << R.GetStudentId() << '\n'
      << "Semester:   " << R.GetSemester() << '\n';
   for(unsigned i = 0; i < R.GetCount(); i++)
     os << R.GetResult(i) << '\n';
  os << "Number of Units = " << R.GetCount() << '\n'
     << "Total Credits = " << R.ComputeCredits() << '\n';
   return os;
 }
References Registration::ComputeCredits(), Registration::GetCount(), Registration::GetResult(), Registration::GetSemester(), and Registration::GetStudentId().
operator>>()
istream& operator>> (istream & input, Registration & R)
Operator overload for input.
Parameters
input is the input stream
R is the object for Registration
Definition at line 66 of file REGIST.CPP.
 {
     string tempStr;
     getline(input, tempStr, ',');
     R.SetStudentId(stol(tempStr));
     getline(input, tempStr, ',');
     R.SetSemester(stoi(tempStr));
     getline(input, tempStr);
     R.SetCount(stoi(tempStr));
   for(unsigned i = 0; i < R.GetCount(); i++)
     input >> R.GetResult(i);
   return input;
 }
References Registration::GetCount(), Registration::GetResult(), Registration::SetCount(), Registration::SetSemester(), and Registration::SetStudentId().