Lab 4: classes/RESULT.CPP File Reference
RESULT.CPP File Reference
#include "RESULT.H"
Functions
istream & operator>> (istream &input, Result &U)
Operator overload for input.
ostream & operator<< (ostream &os, const Result &C)
Operator overload for output.
Function Documentation
operator<<()
ostream& operator<< (ostream & os, const Result & U)
Operator overload for output.
Parameters
os is the output stream
U is the object for Unit
Definition at line 126 of file RESULT.CPP.
 {
     os << C.GetUnit() << '\n'
        << "  Marks: " << C.GetMark() << '\n'
        << C.GetDate() << '\n';
   return os;
 }
References Result::GetDate(), Result::GetMark(), and Result::GetUnit().
operator>>()
istream& operator>> (istream & input, Result & U)
Operator overload for input.
Parameters
input is the input stream
U is the object for Unit
Definition at line 98 of file RESULT.CPP.
 {
     string tempStr;
     getline(input, tempStr, ',');
     U.SetUnitId(tempStr);
     getline(input, tempStr, ',');
     U.SetUnitName(tempStr);
     getline(input, tempStr, ',');
     U.SetCredits(stoi(tempStr));
     getline(input, tempStr, ',');
     U.SetMark(stoi(tempStr));
     getline(input, tempStr, '/');
     U.SetDay(stoi(tempStr));
     getline(input, tempStr, '/');
     U.SetMonthNum(stoi(tempStr));
     getline(input, tempStr);
     U.SetYear(stoi(tempStr));
     return input;
 }
References Result::SetCredits(), Result::SetDay(), Result::SetMark(), Result::SetMonthNum(), Result::SetUnitId(), Result::SetUnitName(), and Result::SetYear().