Lab 4: C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 2/Lab 4/codeblocks - WS2/classes/unitTest/RegistrationTest.hpp File Reference
RegistrationTest.hpp File Reference
#include <iostream>
#include "TestLib.hpp"
#include "../REGIST.H"
Functions
void RegistrationTest ()
Function Documentation
RegistrationTest()
void RegistrationTest ()
Definition at line 14 of file RegistrationTest.hpp.
 {
     header("REGISTRATION TEST");
     section("Test Default Constructor");
     Registration v1;
     require<int>(v1.GetStudentId(), 0, "Student ID should be 0");
     require<int>(v1.GetSemester(), 0, "Semester should be 0");
     require<int>(v1.GetCount(), 0, "Count should be 0");
     section("Test Set Count to 2");
     v1.SetCount(2);
     require<int>(v1.GetCount(), 2, "Count should be 2");
     section("Test Set Student ID to 555");
     v1.SetStudentId(555);
     require<int>(v1.GetStudentId(), 555, "Student ID should be 555");
     section("Test Set Semester to 6");
     v1.SetSemester(6);
     require<int>(v1.GetSemester(), 6, "Semester should be 6");
     section("Test Get Result from Registration list");
     require<int>(v1.GetResult(1).GetMark(), 0, "The default mark of the unit in index 1 is 0");
 }
References Registration::SetCount(), Registration::SetSemester(), and Registration::SetStudentId().
Referenced by main().