Lab 10: C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 10/codeblocks/classes/TIME.CPP File Reference
TIME.CPP File Reference
#include "TIME.H"
#include <iostream>
#include <iomanip>
Functions
istream & operator>> (istream &input, Time &T)
Operator overload for input.
ostream & operator<< (ostream &os, const Time &T)
Operator overload for output.
Function Documentation
operator<<()
ostream& operator<< (ostream & os, const Time & T)
Operator overload for output.
Parameters
os is the output stream
T is the object for Time
Definition at line 69 of file TIME.CPP.
 {
     os << setw(2) << setfill('0')  << T.getHour() << ":" << setw(2) << setfill('0')  << T.getMinute();
   return os;
 }
References Time::getHour(), and Time::getMinute().
operator>>()
istream& operator>> (istream & input, Time & T)
Operator overload for input.
Parameters
input is the input stream
T is the object for Time
Definition at line 56 of file TIME.CPP.
 {
     string tempStr;
     getline(input, tempStr, ':');
     T.setHour(stoi(tempStr));
     getline(input, tempStr);
     T.setMinute(stoi(tempStr));
     return input;
 }
References Time::setHour(), and Time::setMinute().