Lab 4: C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 2/Lab 4/codeblocks - WS2/classes/unitTest/TestMain.cpp File Reference
TestMain.cpp File Reference
#include <iostream>
#include "DateTest.hpp"
#include "RegistrationTest.hpp"
#include "ResultTest.hpp"
Functions
int main (void)
Function Documentation
main()
int main (void)
Definition at line 10 of file TestMain.cpp.
 {
     DateTest();
     cout << endl << endl;
     RegistrationTest();
     cout << endl << endl;
     ResultTest();
 }
References DateTest(), RegistrationTest(), and ResultTest().