Lab 4: classes/UNIT.H File Reference
UNIT.H File Reference
#include <string>
#include <iostream>
Classes
class Unit
It stores unit information.
Functions
istream & operator>> (istream &input, Unit &U)
Operator overload for input.
ostream & operator<< (ostream &os, const Unit &U)
Operator overload for ouput.
Variables
const unsigned UnitNameSize = 40
Function Documentation
operator<<()
ostream& operator<< (ostream & os, const Unit & U)
Operator overload for ouput.
Parameters
os is the output stream
U is the object for Unit
Definition at line 61 of file UNIT.CPP.
 {
   os << "  Unit ID: " << C.GetUnitId() << '\n'
      << "  Unit Name: " << C.GetUnitName() << '\n'
      << "  Credits: " << C.GetCredits();
   return os;
 }
References Unit::GetCredits(), Unit::GetUnitId(), and Unit::GetUnitName().
operator>>()
istream& operator>> (istream & input, Unit & U)
Operator overload for input.
Parameters
input is the input stream
U is the object for Unit
Definition at line 45 of file UNIT.CPP.
 {
     string tempStr;
     getline(input, tempStr, ',');
     U.SetUnitId(tempStr);
     getline(input, tempStr, ',');
     U.SetUnitName(tempStr);
     getline(input, tempStr, ',');
     U.SetCredits(stoi(tempStr));
     return input;
 }
References Unit::SetCredits(), Unit::SetUnitId(), and Unit::SetUnitName().
Variable Documentation
UnitNameSize
const unsigned UnitNameSize = 40
Definition at line 9 of file UNIT.H.