Lab 10: C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 10/codeblocks/classes/WINDRECTYPE.H File Reference
WINDRECTYPE.H File Reference
#include "DATE.H"
#include "TIME.H"
#include "VECTOR.H"
#include <sstream>
Classes
class WindRecType
Logs the data of wind speed, solar radiation, ambient temperature at a specific time and date.
Functions
istream & operator>> (istream &input, WindRecType &W)
Operator overload for input.
ostream & operator<< (ostream &os, WindRecType &W)
Operator overload for output.
Function Documentation
operator<<()
ostream& operator<< (ostream & os, WindRecType & W)
Operator overload for output.
Parameters
os is the output stream
W is the object for WindRecType
Definition at line 96 of file WINDRECTYPE.CPP.
 {
   os << W.getDate() << "  Time: " << W.getTime() << "  Speed: " << W.getSpeed() << "\n";
   return os;
 }
References WindRecType::getDate(), WindRecType::getSpeed(), and WindRecType::getTime().
operator>>()
istream& operator>> (istream & input, WindRecType & W)
Operator overload for input.
Parameters
input is the input stream
W is the object for WindRecType
Definition at line 91 of file WINDRECTYPE.CPP.
 {
     return input;
 }