Lab 10: Date Class Reference
Date Class Reference
It stores a date. Specifically in the format of dd/mm/yyyy.
#include <DATE.H>
Public Member Functions
Date ()
Date (unsigned day, unsigned month, unsigned year)
unsigned GetDay () const
void SetDay (unsigned day)
unsigned GetMonthNum () const
void SetMonthNum (unsigned month)
string GetMonthName () const
unsigned GetYear () const
void SetYear (unsigned year)
bool operator< (const Date &d) const
bool operator> (const Date &d) const
bool operator== (const Date &d) const
void print_date ()
Private Member Functions
string ConvertMonth (unsigned month) const
Private Attributes
unsigned int m_day
unsigned int m_month
unsigned int m_year
Detailed Description
It stores a date. Specifically in the format of dd/mm/yyyy.
Author
Noor Hidayat
Definition at line 14 of file DATE.H.
Constructor & Destructor Documentation
Date() [1/2]
Date::Date ()
The Date default constructor initializes day to 0, month to 1, and date to 0.
Definition at line 3 of file DATE.CPP.
 {
     m_day = 0;
     m_month = 1;
     m_year = 0;
 }
References m_day, m_month, and m_year.
Date() [2/2]
Date::Date (unsigned day, unsigned month, unsigned year)
Date Constructor
Parameters
day The day of the date
month The month of the date in string
year The year of the date
Definition at line 10 of file DATE.CPP.
 {
     SetDay(day);
     SetMonthNum(month);
     m_year = year;
 }
References m_year, SetDay(), and SetMonthNum().
Member Function Documentation
ConvertMonth()
string Date::ConvertMonth (unsigned month) const private
Converts numerical month to string month's name
Parameters
month Contains the numerical month
Definition at line 68 of file DATE.CPP.
 {
     string monthName;
     switch (month)
     {
     case 1:
         monthName = "January";
         break;
     case 2:
         monthName = "February";
         break;
     case 3:
         monthName = "March";
         break;
     case 4:
         monthName = "April";
         break;
     case 5:
         monthName = "May";
         break;
     case 6:
         monthName = "June";
         break;
     case 7:
         monthName = "July";
         break;
     case 8:
         monthName = "August";
         break;
     case 9:
         monthName = "September";
         break;
     case 10:
         monthName = "October";
         break;
     case 11:
         monthName = "November";
         break;
     case 12:
         monthName = "December";
         break;
     default:
         cout << "ERROR: Invalid month.";
         break;
     };
     return monthName;
 }
Referenced by GetMonthName().
GetDay()
unsigned Date::GetDay () const
Get the day of the month
Definition at line 17 of file DATE.CPP.
 {
     return m_day;
 }
References m_day.
Referenced by std::hash< Date >::operator()(), operator<<(), print_date(), and WindRecType::testOutput().
GetMonthName()
string Date::GetMonthName () const
Get the month's named value
Definition at line 53 of file DATE.CPP.
 {
     return ConvertMonth(m_month);
 }
References ConvertMonth(), and m_month.
Referenced by operator<<(), and print_date().
GetMonthNum()
unsigned Date::GetMonthNum () const
Get the month's numerical value
Definition at line 35 of file DATE.CPP.
 {
     return m_month;
 }
References m_month.
Referenced by WindLogData::getAverageBst(), WindLogData::getStdBst(), std::hash< Date >::operator()(), and WindRecType::testOutput().
GetYear()
unsigned Date::GetYear () const
Get the year
Definition at line 58 of file DATE.CPP.
 {
     return m_year;
 }
References m_year.
Referenced by WindLogData::getAverageBst(), WindLogData::getStdBst(), std::hash< Date >::operator()(), operator<<(), print_date(), and WindRecType::testOutput().
operator<()
bool Date::operator< (const Date & d) const
Operator overload for the < to check whether Date is earlier
Parameters
d Holds the Date obj
Definition at line 117 of file DATE.CPP.
 {
     if (m_year != d.m_year)
         return m_year < d.m_year;
     if (m_month != d.m_month)
         return m_month < d.m_month;
     return m_day < d.m_day;
 }
References m_day, m_month, and m_year.
operator==()
bool Date::operator== (const Date & d) const
Operator overload for the == to check whether Dates are equal
Parameters
d Holds the Date obj
Definition at line 164 of file DATE.CPP.
 {
     return m_day == other.m_day
            && m_month == other.m_month
            && m_year == other.m_year;
 }
References m_day, m_month, and m_year.
operator>()
bool Date::operator> (const Date & d) const
Operator overload for the < to check whether Date is later
Parameters
d Holds the Date obj
Definition at line 126 of file DATE.CPP.
 {
     if (m_year != d.m_year)
         return m_year > d.m_year;
     if (m_month != d.m_month)
         return m_month > d.m_month;
     return m_day > d.m_day;
 }
References m_day, m_month, and m_year.
print_date()
void Date::print_date ()
Definition at line 136 of file DATE.CPP.
 {
     cout << "Date: " << GetDay() << " " << GetMonthName() << " " << GetYear() << endl;
 }
References GetDay(), GetMonthName(), and GetYear().
SetDay()
void Date::SetDay (unsigned day)
Set the day of the month
Parameters
day Contains the day of the month to set to
Definition at line 22 of file DATE.CPP.
 {
     if (day > 31 || day < 1)
     {
         m_day = 0;
     }
     else
     {
         m_day = day;
     }
 }
References m_day.
Referenced by Date(), operator>>(), and WindRecType::setDate().
SetMonthNum()
void Date::SetMonthNum (unsigned month)
Set the month in numerical value
Parameters
month Contains the month to set to. If month is not within 1 - 12 , defaults to 0
Definition at line 40 of file DATE.CPP.
 {
     if (month > 12 || month < 1)
     {
         m_month = 1;
     }
     else
     {
         m_month = month;
     }
 }
References m_month.
Referenced by Date(), operator>>(), and WindRecType::setDate().
SetYear()
void Date::SetYear (unsigned year)
Set the year
Parameters
year Contains the year to set to
Definition at line 63 of file DATE.CPP.
 {
     m_year = year;
 }
References m_year.
Referenced by operator>>(), and WindRecType::setDate().
Member Data Documentation
m_day
unsigned int Date::m_day private
Stores the day of the month in integer
Definition at line 98 of file DATE.H.
Referenced by Date(), GetDay(), operator<(), operator==(), operator>(), and SetDay().
m_month
unsigned int Date::m_month private
Stores a numerical value of the month
Definition at line 100 of file DATE.H.
Referenced by Date(), GetMonthName(), GetMonthNum(), operator<(), operator==(), operator>(), and SetMonthNum().
m_year
unsigned int Date::m_year private
Stores the year in integer
Definition at line 102 of file DATE.H.
Referenced by Date(), GetYear(), operator<(), operator==(), operator>(), and SetYear().
The documentation for this class was generated from the following files:
C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 10/codeblocks/classes/DATE.H
C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 10/codeblocks/classes/DATE.CPP