Lab 4: Unit Class Reference
Unit Class Reference
It stores unit information.
#include <UNIT.H>
Public Member Functions
Unit ()
Unit (const string name, const string id, unsigned cred)
A constructor for the Unit Class.
unsigned GetCredits () const
Get the credit of the Unit.
void SetCredits (unsigned cred)
Sets Credit of the Unit.
const string GetUnitName () const
Get the name of the Unit.
void SetUnitName (const string name)
Sets the name of the Unit.
const string GetUnitId () const
Get the unit's ID.
void SetUnitId (const string id)
Set the unit's ID.
Private Attributes
string m_unit_name
string m_unit_id
int m_credits
Detailed Description
It stores unit information.
The unit contains the unit name, unit ID, and credits
Author
Noor Hidayat
Definition at line 20 of file UNIT.H.
Constructor & Destructor Documentation
Unit() [1/2]
Unit::Unit ()
Definition at line 3 of file UNIT.CPP.
 {
     m_unit_name = "NULL";
     m_unit_id = "NULL";
     m_credits = 0;
 }
References m_credits, m_unit_id, and m_unit_name.
Unit() [2/2]
Unit::Unit (const string name, const string id, unsigned cred)
A constructor for the Unit Class.
Parameters
name Contains the name of the Unit
id Contains the ID of the Unit
cred Contains the credit of the Unit
Definition at line 10 of file UNIT.CPP.
 {
     m_unit_name = name;
     m_unit_id = id;
     m_credits = cred;
 }
References m_credits, m_unit_id, and m_unit_name.
Member Function Documentation
GetCredits()
unsigned Unit::GetCredits () const
Get the credit of the Unit.
Definition at line 18 of file UNIT.CPP.
 {
     return m_credits;
 }
References m_credits.
Referenced by Result::GetCredits(), and operator<<().
GetUnitId()
const string Unit::GetUnitId () const
Get the unit's ID.
Definition at line 37 of file UNIT.CPP.
{
     return m_unit_id;
 }
References m_unit_id.
Referenced by Result::GetUnitId(), and operator<<().
GetUnitName()
const string Unit::GetUnitName () const
Get the name of the Unit.
Definition at line 29 of file UNIT.CPP.
{
     return m_unit_name;
 }
References m_unit_name.
Referenced by Result::GetUnitName(), and operator<<().
SetCredits()
void Unit::SetCredits (unsigned cred)
Sets Credit of the Unit.
Parameters
cred Contains the credit to set to
Definition at line 23 of file UNIT.CPP.
 {
     m_credits = cred;
 }
References m_credits.
Referenced by operator>>(), and Result::SetCredits().
SetUnitId()
void Unit::SetUnitId (const string id)
Set the unit's ID.
Parameters
id Contains the ID to set the unit's ID to
Definition at line 41 of file UNIT.CPP.
{
     m_unit_id = id;
 }
References m_unit_id.
Referenced by operator>>(), and Result::SetUnitId().
SetUnitName()
void Unit::SetUnitName (const string name)
Sets the name of the Unit.
Parameters
name Contains the name to set the unit's name to
Definition at line 33 of file UNIT.CPP.
{
     m_unit_name = name;
 }
References m_unit_name.
Referenced by operator>>(), and Result::SetUnitName().
Member Data Documentation
m_credits
int Unit::m_credits private
Store the unit's credits
Definition at line 69 of file UNIT.H.
Referenced by GetCredits(), SetCredits(), and Unit().
m_unit_id
string Unit::m_unit_id private
Store the unit's ID
Definition at line 67 of file UNIT.H.
Referenced by GetUnitId(), SetUnitId(), and Unit().
m_unit_name
string Unit::m_unit_name private
Store the unit's name
Definition at line 65 of file UNIT.H.
Referenced by GetUnitName(), SetUnitName(), and Unit().
The documentation for this class was generated from the following files:
classes/UNIT.H
classes/UNIT.CPP