Lab 4: Result Class Reference
Result Class Reference
It stores a unit, its marks and marked date of the unit.
#include <RESULT.H>
Public Member Functions
Result ()
Result (Unit &unit, Date &date, float mark)
This is the parameterized constructor.
unsigned GetMark () const
Get the marked result.
void SetMark (const unsigned mark)
int GetCredits () const
void SetCredits (const unsigned cred)
const string GetUnitName () const
void SetUnitName (const string name)
const string GetUnitId () const
void SetUnitId (const string id)
unsigned GetDay () const
void SetDay (unsigned day)
const unsigned GetMonthNum () const
void SetMonthNum (unsigned month)
unsigned GetYear () const
void SetYear (unsigned year)
Unit GetUnit () const
Unit SetUnit (Unit &unit)
Date GetDate () const
Private Attributes
Unit m_unit
Date m_date
float m_mark
Detailed Description
It stores a unit, its marks and marked date of the unit.
Author
Noor Hidayat
Definition at line 15 of file RESULT.H.
Constructor & Destructor Documentation
Result() [1/2]
Result::Result ()
Definition at line 3 of file RESULT.CPP.
 {
     m_unit = Unit();
     m_date = Date();
     m_mark = 0;
 }
References m_date, m_mark, and m_unit.
Result() [2/2]
Result::Result (Unit & unit, Date & date, float mark)
This is the parameterized constructor.
Parameters
unit Contains the unit object which includes the unit name and code
date is the date of when the unit is marked
mark Is the mark that the student got for that specific unit
Definition at line 10 of file RESULT.CPP.
 {
     m_unit = unit;
     m_date = date;
     m_mark = mark;
 }
References m_date, m_mark, and m_unit.
Member Function Documentation
GetCredits()
int Result::GetCredits () const
Get the credit of the unit
Definition at line 27 of file RESULT.CPP.
 {
   return m_unit.GetCredits();
 }
References Unit::GetCredits(), and m_unit.
GetDate()
Date Result::GetDate () const
Get the Date
Definition at line 93 of file RESULT.CPP.
 {
     return m_date;
 }
References m_date.
Referenced by operator<<().
GetDay()
unsigned Result::GetDay () const
Get the day of the month
Definition at line 53 of file RESULT.CPP.
 {
     return m_date.GetDay();
 }
References Date::GetDay(), and m_date.
GetMark()
unsigned Result::GetMark () const inline
Get the marked result.
Definition at line 17 of file RESULT.CPP.
 {
   return m_mark;
 }
References m_mark.
Referenced by operator<<().
GetMonthNum()
const unsigned Result::GetMonthNum () const
Get the month's name
Definition at line 63 of file RESULT.CPP.
 {
     return m_date.GetMonthNum();
 }
References Date::GetMonthNum(), and m_date.
GetUnit()
Unit Result::GetUnit () const
Get the Unit
Definition at line 83 of file RESULT.CPP.
 {
     return m_unit;
 }
References m_unit.
Referenced by operator<<().
GetUnitId()
const string Result::GetUnitId () const
Get the Unit's ID
Definition at line 45 of file RESULT.CPP.
{
      return m_unit.GetUnitId();
 }
References Unit::GetUnitId(), and m_unit.
GetUnitName()
const string Result::GetUnitName () const
Get the Unit's name
Definition at line 37 of file RESULT.CPP.
{
     return m_unit.GetUnitName();
 }
References Unit::GetUnitName(), and m_unit.
GetYear()
unsigned Result::GetYear () const
Get the year
Definition at line 73 of file RESULT.CPP.
 {
     return m_date.GetYear();
 }
References Date::GetYear(), and m_date.
SetCredits()
void Result::SetCredits (const unsigned cred)
Set the credit of the unit
Parameters
cred contains the credit of the unit to set to
Definition at line 32 of file RESULT.CPP.
 {
     m_unit.SetCredits(cred);
 }
References m_unit, and Unit::SetCredits().
Referenced by operator>>().
SetDay()
void Result::SetDay (unsigned day)
Set the day of the month
Parameters
day Contains the day of the month to set to
Definition at line 58 of file RESULT.CPP.
 {
     m_date.SetDay(day);
 }
References m_date, and Date::SetDay().
Referenced by operator>>().
SetMark()
void Result::SetMark (const unsigned mark) inline
Set the mark of the unit
Parameters
mark contains the mark of the unit to set to
Definition at line 22 of file RESULT.CPP.
 {
   m_mark = mark;
 }
References m_mark.
Referenced by operator>>().
SetMonthNum()
void Result::SetMonthNum (unsigned month)
Set the month's name
Parameters
month Contains the month to set to
Definition at line 68 of file RESULT.CPP.
 {
     m_date.SetMonthNum(month);
 }
References m_date, and Date::SetMonthNum().
Referenced by operator>>().
SetUnit()
Unit Result::SetUnit (Unit & unit)
Set the Unit
Definition at line 88 of file RESULT.CPP.
 {
     m_unit = unit;
 }
References m_unit.
SetUnitId()
void Result::SetUnitId (const string id)
Set the Unit's ID
Parameters
id Contains the ID to set the Unit's ID to
Definition at line 49 of file RESULT.CPP.
{
       m_unit.SetUnitId(id);
 }
References m_unit, and Unit::SetUnitId().
Referenced by operator>>().
SetUnitName()
void Result::SetUnitName (const string name)
Set the Unit's name
Parameters
name contains the name to set the unit's name to
Definition at line 41 of file RESULT.CPP.
{
       m_unit.SetUnitName(name);
 }
References m_unit, and Unit::SetUnitName().
Referenced by operator>>().
SetYear()
void Result::SetYear (unsigned year)
Set the year
Parameters
year Contains the year to set to
Definition at line 78 of file RESULT.CPP.
 {
     m_date.SetYear(year);
 }
References m_date, and Date::SetYear().
Referenced by operator>>().
Member Data Documentation
m_date
Date Result::m_date private
Stores the date of unit marked
Definition at line 124 of file RESULT.H.
Referenced by GetDate(), GetDay(), GetMonthNum(), GetYear(), Result(), SetDay(), SetMonthNum(), and SetYear().
m_mark
float Result::m_mark private
Stores the mark of the unit
Definition at line 126 of file RESULT.H.
Referenced by GetMark(), Result(), and SetMark().
m_unit
Unit Result::m_unit private
Stores the unit
Definition at line 122 of file RESULT.H.
Referenced by GetCredits(), GetUnit(), GetUnitId(), GetUnitName(), Result(), SetCredits(), SetUnit(), SetUnitId(), and SetUnitName().
The documentation for this class was generated from the following files:
classes/RESULT.H
classes/RESULT.CPP