Lab 4: Registration Class Reference
Registration Class Reference
It stores information about the student's units' result in the specified semester.
#include <REGIST.H>
Public Member Functions
Registration ()
unsigned ComputeCredits () const
Computes the sum of credit of the unit.
unsigned GetCount () const
Get the number of units to display.
void SetCount (unsigned count)
Set the number of units to display.
const long GetStudentId () const
Get the number of students.
void SetStudentId (const long id)
set the student ID
const unsigned GetSemester () const
Get the semester of the units.
void SetSemester (const unsigned semester)
Set the semester of the units.
Result & GetResult (int index)
Get the Unit in the specified index of the array list.
void SetResult (const Result result, const unsigned index)
Sets the Result of a unit into the specified index of the array list.
void print_registrations ()
Private Attributes
long m_studentId
unsigned m_semester
unsigned m_count
Result m_units [MAX_UNITS]
Detailed Description
It stores information about the student's units' result in the specified semester.
A student that has been registered will contain a student id, the semester, units.
The registration contains the list of units Results including its name, unit code, and marks. In addition to the student's ID, semester. It also displays the number of course taken by the student, and the student's total credit.
Author
Noor Hidayat
Definition at line 27 of file REGIST.H.
Constructor & Destructor Documentation
Registration()
Registration::Registration ()
Definition at line 4 of file REGIST.CPP.
 {
     m_studentId = 0;
     m_semester = 0;
     m_count = 0;
 }
References m_count, m_semester, and m_studentId.
Member Function Documentation
ComputeCredits()
unsigned Registration::ComputeCredits () const
Computes the sum of credit of the unit.
Definition at line 11 of file REGIST.CPP.
 {
   unsigned sum = 0;
   for(unsigned i = 0; i < m_count; i++)
     sum += m_units[i].GetCredits();
   return sum;
 }
References m_count, and m_units.
Referenced by operator<<().
GetCount()
unsigned Registration::GetCount () const
Get the number of units to display.
Definition at line 20 of file REGIST.CPP.
 {
   return m_count;
 }
References m_count.
Referenced by operator<<(), operator>>(), and print_registrations().
GetResult()
Result & Registration::GetResult (int index)
Get the Unit in the specified index of the array list.
Parameters
index Specifies which index of the list to retrieve Unit
Definition at line 45 of file REGIST.CPP.
 {
     return m_units[index];
 }
References m_units.
Referenced by operator<<(), and operator>>().
GetSemester()
const unsigned Registration::GetSemester () const
Get the semester of the units.
Definition at line 37 of file REGIST.CPP.
{
     return m_semester;
 }
References m_semester.
Referenced by operator<<(), and print_registrations().
GetStudentId()
const long Registration::GetStudentId () const
Get the number of students.
Definition at line 29 of file REGIST.CPP.
{
     return m_studentId;
 }
References m_studentId.
Referenced by operator<<(), and print_registrations().
print_registrations()
void Registration::print_registrations ()
Definition at line 59 of file REGIST.CPP.
 {
     cout << "Student ID: " << GetStudentId() << '\n'
     << "Semester: " << GetSemester() << '\n'
     << "Number of Units: " << GetCount() << endl;
 }
References GetCount(), GetSemester(), and GetStudentId().
SetCount()
void Registration::SetCount (unsigned count)
Set the number of units to display.
Parameters
count is the positive integer of the number of units
Definition at line 25 of file REGIST.CPP.
{
     m_count = count;
 }
References m_count.
Referenced by operator>>().
SetResult()
void Registration::SetResult (const Result result, const unsigned index)
Sets the Result of a unit into the specified index of the array list.
Parameters
result is the Result object that contains the unit and marked date
index Specifies which index of the list to set Unit
Definition at line 50 of file REGIST.CPP.
 {
     if (index >= 0 && index < MAX_UNITS)
     {
         m_units[index] = result;
     }
 }
References m_units, and MAX_UNITS.
SetSemester()
void Registration::SetSemester (const unsigned semester)
Set the semester of the units.
Parameters
semester contains the semester to set to
Definition at line 41 of file REGIST.CPP.
{
     m_semester = semester;
 }
References m_semester.
Referenced by operator>>().
SetStudentId()
void Registration::SetStudentId (const long id)
set the student ID
Parameters
id contains the student ID to set to
Definition at line 33 of file REGIST.CPP.
{
     m_studentId = id;
 }
References m_studentId.
Referenced by operator>>().
Member Data Documentation
m_count
unsigned Registration::m_count private
Stores the number of units
Definition at line 91 of file REGIST.H.
Referenced by ComputeCredits(), GetCount(), Registration(), and SetCount().
m_semester
unsigned Registration::m_semester private
Stores the semester
Definition at line 89 of file REGIST.H.
Referenced by GetSemester(), Registration(), and SetSemester().
m_studentId
long Registration::m_studentId private
Stores the student's ID
Definition at line 87 of file REGIST.H.
Referenced by GetStudentId(), Registration(), and SetStudentId().
m_units
Result Registration::m_units[MAX_UNITS] private
Stores a list of Units
Definition at line 93 of file REGIST.H.
Referenced by ComputeCredits(), GetResult(), and SetResult().
The documentation for this class was generated from the following files:
classes/REGIST.H
classes/REGIST.CPP