Lab 10: Time Class Reference
Time Class Reference
It stores the Time.
#include <TIME.H>
Public Member Functions
Time ()
Time (int hour, int minute)
const int getHour () const
const int getMinute () const
void setHour (const int hour)
void setMinute (const int minute)
bool operator== (Time &obj)
void print_time () const
Private Attributes
int m_hour
int m_minute
Detailed Description
It stores the Time.
The Time includes the hour and the minute
Author
Noor Hidayat
Definition at line 10 of file TIME.H.
Constructor & Destructor Documentation
Time() [1/2]
Time::Time ()
The Time default constructor initializes hour and minute to a value of 0.
Definition at line 5 of file TIME.CPP.
 {
     m_hour = 0;
     m_minute = 0;
 }
References m_hour, and m_minute.
Time() [2/2]
Time::Time (int hour, int minute)
Time Constructor
Parameters
hour The hour of the time
minute The minute of the time
Definition at line 11 of file TIME.CPP.
 {
     m_hour = hour;
     m_minute = minute;
 }
References m_hour, and m_minute.
Member Function Documentation
getHour()
const int Time::getHour () const
Get the hour of the time
Definition at line 17 of file TIME.CPP.
 {
     return m_hour;
 }
References m_hour.
Referenced by operator<<(), operator==(), and print_time().
getMinute()
const int Time::getMinute () const
Get the minute of the time
Definition at line 22 of file TIME.CPP.
 {
     return m_minute;
 }
References m_minute.
Referenced by operator<<(), operator==(), and print_time().
operator==()
bool Time::operator== (Time & obj)
Definition at line 37 of file TIME.CPP.
 {
     if ((this->getHour() == obj.getHour()) && this->getMinute() == obj.getMinute()) {
         return true;
     } else {
         return false;
     }
 }
References getHour(), and getMinute().
print_time()
void Time::print_time () const
Definition at line 47 of file TIME.CPP.
 {
     ostringstream ss;
     ss << setw(2) << setfill('0')  << getHour() << ":" << setw(2) << setfill('0')  << getMinute();
     string s = ss.str();
     cout << s << endl;
 }
References getHour(), and getMinute().
setHour()
void Time::setHour (const int hour)
Set the hour of the time
Parameters
hour Contains the hour of the time to set to
Definition at line 27 of file TIME.CPP.
 {
     m_hour = hour;
 }
References m_hour.
Referenced by operator>>(), and WindRecType::setTime().
setMinute()
void Time::setMinute (const int minute)
Set the minute of the time
Parameters
minute Contains the minute of the time to set to
Definition at line 32 of file TIME.CPP.
 {
     m_minute = minute;
 }
References m_minute.
Referenced by operator>>(), and WindRecType::setTime().
Member Data Documentation
m_hour
int Time::m_hour private
Stores an integer hour of the time
Definition at line 62 of file TIME.H.
Referenced by getHour(), setHour(), and Time().
m_minute
int Time::m_minute private
Stores an integer minute of the time
Definition at line 64 of file TIME.H.
Referenced by getMinute(), setMinute(), and Time().
The documentation for this class was generated from the following files:
C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 10/codeblocks/classes/TIME.H
C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 10/codeblocks/classes/TIME.CPP