Lab 10: WindLogData Class Reference
WindLogData Class Reference
Manages all wind logs data in a vector. Wind logs data can be read from file and inputted into the vector. Available methods such as printing the wind logs for specific year and month.
#include <WINDLOGDATA.H>
Public Types
enum Mode { SPEED, TEMP, SOLARRAD }
Represents the different operating modes available for data processing.
Public Member Functions
WindLogData ()
Default constructor for WindLogData class.
void setMode (Mode newMode)
Setter method for the operating mode.
bool readFile (string fileName)
This function reads CSV file containing wind logs.
void printSpeedAndStD (string year, string month)
Prints the wind speed and temperature for a specific year and month.
void printTempAndStd (string year)
Prints the wind speed and temperature for a specific year.
void printSolarRadiation (string year)
Prints the total solar radiation each month for specific year.
void writeToCSV (string fileName, string year)
Writes wind speed, temperature, solar radiation, date and time to CSV file for a specific year.
void sPCC (string month)
Calculates and prints the Solar panel correlation coefficient for a specified month.
void destroy ()
Destroy all variables to their default states.
Static Public Member Functions
static void getAverageBst (Date &date)
Retrieves and displays the average wind speed, temperature, and solar radiation for a specific date using the Binary Search Tree.
static void getStdBst (Date &date)
Retrieves and displays the standard deviation of wind speed, temperature, and solar radiation for a specific date using the Binary Search Tree.
Private Member Functions
float getAverageSpeed (string year, string month)
Get the average wind speed for the specific month and year.
float getAverageTemp (string year, string month)
Get the average temperature for the specific month and year.
float getAverageSolarRad (string year, string month)
Get the average solar radiation for the specific month and year.
float getTotalSolarRadiationMonth (string year, string month)
Get the total solar radiation for the specific month and year.
float getStandardDeviationSpeed (string year, string month, float mean)
Get the standard deviation for speed of the year and month.
float getStandardDeviationTemp (string year, string month, float mean)
Get the standard deviation for temperature of the year and month.
float getStandardDeviationSolarRad (string year, string month, float mean)
Get the standard deviation for solar radiation of the year and month.
string numToMonth (string num)
Converts month of year in numeric to alphabets (eg. 1 to January)
void setTargetYearMonth (int year, int month)
Sets the target year and month for which data is to be processed.
void reset ()
Resets all static member variables to their default states.
Private Attributes
Bst< Date > bst
Static Private Attributes
static Mode mode
static unordered_map< Date, Vector< WindRecType > > dataMap
static float totalValue
static float averageValue
static int totalCount
static int targetYear
static int targetMonth
Detailed Description
Manages all wind logs data in a vector. Wind logs data can be read from file and inputted into the vector. Available methods such as printing the wind logs for specific year and month.
Contains data of inputted wind logs and methods to print and write data to CSV file.
Author
Noor Hidayat
Definition at line 26 of file WINDLOGDATA.H.
Member Enumeration Documentation
Mode
enum WindLogData::Mode
Represents the different operating modes available for data processing.
The available modes are SPEED for wind speed, TEMP for temperature, and SOLARRAD for solar radiation. These modes determine which data is processed and output by the WindLogData class.
Enumerator
SPEED
TEMP
SOLARRAD
Definition at line 45 of file WINDLOGDATA.H.
     {
         SPEED,
         TEMP,
         SOLARRAD
     };
Constructor & Destructor Documentation
WindLogData()
WindLogData::WindLogData ()
Default constructor for WindLogData class.
This constructor initializes a new instance of the WindLogData class, setting up the necessary resources for managing wind log data.
Definition at line 14 of file WINDLOGDATA.CPP.
 {
     dataMap.clear();
     reset();
 }
Member Function Documentation
destroy()
void WindLogData::destroy ()
Destroy all variables to their default states.
Definition at line 466 of file WINDLOGDATA.CPP.
 {
     reset();
     dataMap.clear();
     bst.deleteTree();
 }
Referenced by readFiles().
getAverageBst()
void WindLogData::getAverageBst (Date & date) static
Retrieves and displays the average wind speed, temperature, and solar radiation for a specific date using the Binary Search Tree.
Parameters
date - Date object representing the target date.
Definition at line 474 of file WINDLOGDATA.CPP.
 {
     Vector<WindRecType> logs = dataMap[date];
     if (targetYear == -1)
     {
         if ((date.GetMonthNum()) == targetMonth)
         {
             for(int i = 0; i < logs.getSize(); i++)
             {
                 if (mode == SPEED)
                 {
                     totalValue += logs.At(i).getSpeed();
                 }
                 else if (mode == TEMP)
                 {
                     totalValue += logs.At(i).getAmbientAirTemp();
                 }
                 else if (mode == SOLARRAD)
                 {
                     totalValue += logs.At(i).getSolarRad();
                 }
                 totalCount++;
             }
         }
     }
     else
     {
         if ((date.GetYear()) == targetYear && (date.GetMonthNum()) == targetMonth)
         {
             for(int i = 0; i < logs.getSize(); i++)
             {
                 if (mode == SPEED)
                 {
                     totalValue += logs.At(i).getSpeed();
                 }
                 else if (mode == TEMP)
                 {
                     totalValue += logs.At(i).getAmbientAirTemp();
                 }
                 else if (mode == SOLARRAD)
                 {
                     totalValue += logs.At(i).getSolarRad();
                 }
                 totalCount++;
             }
         }
     }
 }
References Vector< T >::At(), WindRecType::getAmbientAirTemp(), Date::GetMonthNum(), Vector< T >::getSize(), WindRecType::getSolarRad(), WindRecType::getSpeed(), and Date::GetYear().
getAverageSolarRad()
float WindLogData::getAverageSolarRad (string year, string month) private
Get the average solar radiation for the specific month and year.
Parameters
year - year to be specified month - month to be specified in numeric(1 to 12)
Returns
float - returns average solar radiation, 0 if no data is found
Definition at line 362 of file WINDLOGDATA.CPP.
 {
     reset();
     setMode(SOLARRAD);
     setTargetYearMonth(stoi(year), stoi(month));
     bst.inOrder(getAverageBst);
     float averageSolar = totalValue / totalCount;
     if(isnan(averageSolar))
     {
         return 0;
     }
     else
     {
         return averageSolar;
     }
 }
getAverageSpeed()
float WindLogData::getAverageSpeed (string year, string month) private
Get the average wind speed for the specific month and year.
Parameters
year - year to be specified month - month to be specified in numeric(1 to 12)
Returns
float - returns average wind speed in km/h, 0 if no data is found
Definition at line 326 of file WINDLOGDATA.CPP.
 {
     reset();
     setMode(SPEED);
     setTargetYearMonth(stoi(year), stoi(month));
     bst.inOrder(getAverageBst);
     float averageSpeed = totalValue / totalCount;
     if(isnan(averageSpeed))
     {
         return 0;
     }
     else
     {
         return averageSpeed;
     }
 }
getAverageTemp()
float WindLogData::getAverageTemp (string year, string month) private
Get the average temperature for the specific month and year.
Parameters
year - year to be specified month - month to be specified in numeric(1 to 12)
Returns
float - returns average temperature in degrees C, 0 if no data is found
Definition at line 344 of file WINDLOGDATA.CPP.
 {
     reset();
     setMode(TEMP);
     setTargetYearMonth(stoi(year), stoi(month));
     bst.inOrder(getAverageBst);
     float averageTemp = totalValue / totalCount;
     if(isnan(averageTemp))
     {
         return 0;
     }
     else
     {
         return averageTemp;
     }
 }
getStandardDeviationSolarRad()
float WindLogData::getStandardDeviationSolarRad (string year, string month, float mean) private
Get the standard deviation for solar radiation of the year and month.
Returns
float - returns the standard deviation value
Definition at line 270 of file WINDLOGDATA.CPP.
 {
     reset();
     setMode(SOLARRAD);
     averageValue = mean;
     setTargetYearMonth(stoi(year), stoi(month));
     bst.inOrder(getStdBst);
     return sqrt(totalValue / (totalCount - 1));
 }
getStandardDeviationSpeed()
float WindLogData::getStandardDeviationSpeed (string year, string month, float mean) private
Get the standard deviation for speed of the year and month.
Returns
float - returns the standard deviation value
Definition at line 244 of file WINDLOGDATA.CPP.
 {
     reset();
     setMode(SPEED);
     averageValue = mean;
     setTargetYearMonth(stoi(year), stoi(month));
     bst.inOrder(getStdBst);
     return sqrt(totalValue / (totalCount - 1));
 }
getStandardDeviationTemp()
float WindLogData::getStandardDeviationTemp (string year, string month, float mean) private
Get the standard deviation for temperature of the year and month.
Returns
float - returns the standard deviation value
Definition at line 257 of file WINDLOGDATA.CPP.
 {
     reset();
     setMode(TEMP);
     averageValue = mean;
     setTargetYearMonth(stoi(year), stoi(month));
     bst.inOrder(getStdBst);
     return sqrt(totalValue / (totalCount - 1));
 }
getStdBst()
void WindLogData::getStdBst (Date & date) static
Retrieves and displays the standard deviation of wind speed, temperature, and solar radiation for a specific date using the Binary Search Tree.
Parameters
date - Date object representing the target date.
Definition at line 528 of file WINDLOGDATA.CPP.
 {
     Vector<WindRecType> logs = dataMap[date];
     if (targetYear == -1)
     {
         if ((date.GetMonthNum()) == targetMonth)
         {
             for(int i = 0; i < logs.getSize(); i++)
             {
                 if (mode == SPEED)
                 {
                     totalValue += (logs.At(i).getSpeed() - averageValue) * (logs.At(i).getSpeed() - averageValue);
                 }
                 else if (mode == TEMP)
                 {
                     totalValue += (logs.At(i).getAmbientAirTemp() - averageValue) * (logs.At(i).getAmbientAirTemp() - averageValue);
                 }
                 else if (mode == SOLARRAD)
                 {
                     totalValue += (logs.At(i).getSolarRad() - averageValue) * (logs.At(i).getSolarRad() - averageValue);
                 }
                 totalCount++;
             }
         }
     }
     else
     {
         if ((date.GetYear()) == targetYear && (date.GetMonthNum()) == targetMonth)
         {
             for(int i = 0; i < logs.getSize(); i++)
             {
                 if (mode == SPEED)
                 {
                     totalValue += (logs.At(i).getSpeed() - averageValue) * (logs.At(i).getSpeed() - averageValue);
                 }
                 else if (mode == TEMP)
                 {
                     totalValue += (logs.At(i).getAmbientAirTemp() - averageValue) * (logs.At(i).getAmbientAirTemp() - averageValue);
                 }
                 else if (mode == SOLARRAD)
                 {
                     totalValue += (logs.At(i).getSolarRad() - averageValue) * (logs.At(i).getSolarRad() - averageValue);
                 }
                 totalCount++;
             }
         }
     }
 }
References Vector< T >::At(), WindRecType::getAmbientAirTemp(), Date::GetMonthNum(), Vector< T >::getSize(), WindRecType::getSolarRad(), WindRecType::getSpeed(), and Date::GetYear().
getTotalSolarRadiationMonth()
float WindLogData::getTotalSolarRadiationMonth (string year, string month) private
Get the total solar radiation for the specific month and year.
Parameters
year - year to be specified month - month to be specified in numeric(1 to 12)
Returns
float - returns total solar radiation in kWh/m2, 0 if no data is found
Definition at line 380 of file WINDLOGDATA.CPP.
 {
     float totalSolarRadiation = 0;
     for(auto& [key, windLogVect] : dataMap)
     {
         if (key.GetMonthNum() == stoi(month))
         {
             for(int i = 0; i < windLogVect.getSize(); i++)
             {
                 // Don't get the radiation recorded at night
                 if (windLogVect[i].getSolarRad() >= 100)
                 {
                     totalSolarRadiation += windLogVect[i].getSolarRad();
                 }
             }
         }
         else
         {
             if (key.GetMonthNum() == stoi(month) && key.GetYear() == stoi(year))
             {
                 for(int i = 0; i < windLogVect.getSize(); i++)
                 {
                     // Don't get the radiation recorded at night
                     if (windLogVect[i].getSolarRad() >= 100)
                     {
                         totalSolarRadiation += windLogVect[i].getSolarRad();
                     }
                 }
             }
         }
     }
     float solarRadiationInKWH = ((totalSolarRadiation * 1/6)/1000);
     return solarRadiationInKWH;
 }
numToMonth()
string WindLogData::numToMonth (string num) private
Converts month of year in numeric to alphabets (eg. 1 to January)
Parameters
num - numeric representation for month (eg. 1 = January)
Returns
string - returns the month in alphabets (eg. input 1, returns "January")
Definition at line 419 of file WINDLOGDATA.CPP.
 {
     string months[] =
     {
         "Invalid input",
         "January",
         "February",
         "March",
         "April",
         "May",
         "June",
         "July",
         "August",
         "September",
         "October",
         "November",
         "December"
     };
     int monthNum = stoi(month); // Convert month string to integer
     if (monthNum >= 1 && monthNum <= 12)
     {
         return months[monthNum];
     }
     else
     {
         return months[0]; // Return "Invalid input" for out-of-range values
     }
 }
printSolarRadiation()
void WindLogData::printSolarRadiation (string year)
Prints the total solar radiation each month for specific year.
Parameters
year - year (eg. 2016)
Definition at line 306 of file WINDLOGDATA.CPP.
 {
     cout << year << endl;
     for(int i = 1; i <= 12; i++)
     {
         float totalSolarRadiation = round(getTotalSolarRadiationMonth(year, to_string(i))*10)/10;
         if(totalSolarRadiation == 0)
         {
             cout << numToMonth(to_string(i)) << ": No Data" << endl;
         }
         else
         {
             cout << numToMonth(to_string(i)) << ": " << totalSolarRadiation << " kWh/m2" <<endl;
         }
     }
     cout << endl;
 }
printSpeedAndStD()
void WindLogData::printSpeedAndStD (string year, string month)
Prints the wind speed and temperature for a specific year and month.
Parameters
year - year (eg. 2016) month - month in numeric (1 to 12)
Definition at line 228 of file WINDLOGDATA.CPP.
 {
     float averageSpeed = round(getAverageSpeed(year, month)*10)/10;
     float standardDeviation = roundf(getStandardDeviationSpeed(year, month, averageSpeed)*10.0f)/10.0f;
     if(averageSpeed == 0 && standardDeviation == 0)
     {
         cout << numToMonth(month) << " " << year << ": No Data" << '\n' << endl;
     }
     else
     {
         cout << numToMonth(month) << " " << year << ": " << "\nAverage speed: " << averageSpeed << " km/h "
              << "\nSample stdev: " << standardDeviation << "\n" << endl;
     }
 }
Referenced by main().
printTempAndStd()
void WindLogData::printTempAndStd (string year)
Prints the wind speed and temperature for a specific year.
Parameters
year - year (eg. 2016)
Definition at line 283 of file WINDLOGDATA.CPP.
 {
     cout << year << endl;
     for(int i = 1; i <= 12; i++)
     {
         float averageTemp = round(getAverageTemp(year, to_string(i))*10)/10;
         float standardDeviation = roundf(getStandardDeviationTemp(year, to_string(i), averageTemp)*10.0f)/10.0f;
         if(averageTemp == 0)
         {
             cout << numToMonth(to_string(i)) << ": No Data" << endl;
         }
         else
         {
             cout << numToMonth(to_string(i)) << ": average: " << averageTemp << " degrees C, stdev: "
                  << standardDeviation << endl;
         }
     }
     cout << endl;
 }
Referenced by main().
readFile()
bool WindLogData::readFile (string fileName)
This function reads CSV file containing wind logs.
Parameters
fileName - name of file to be read
Returns
bool - returns true if file found and false if file not found
Definition at line 21 of file WINDLOGDATA.CPP.
 {
     ifstream inFile(fileName);
     if(!inFile)
     {
         return false;
     }
     // Read header columns and get the indexes.
     // Then set value to the respective index
     string tempStr;
     int dateTimeColumn;
     int speedColumn;
     int solarRadColumn;
     int temperatureColumn;
     WindRecType windLog;
     string timeDate;
     bool headerTaken = false;
     while (getline(inFile, tempStr))
     {
         if (!tempStr.empty())   // Checks for empty rows
         {
             stringstream ss(tempStr);
             string cellValue;
             int index = 0;
             bool invalidData = false;
             while (getline(ss, cellValue, ','))
             {
                 // Only the first row of the file sets the header indexes
                 if (!headerTaken)
                 {
                     if (cellValue == "WAST")
                     {
                         dateTimeColumn = index;
                     }
                     else if (cellValue == "S")
                     {
                         speedColumn = index;
                     }
                     else if (cellValue == "SR")
                     {
                         solarRadColumn = index;
                     }
                     else if (cellValue == "T")
                     {
                         temperatureColumn = index;
                     }
                 }
                 else
                 {
                     // Checks for invalid data
                     if (cellValue == "N/A" || cellValue.empty() || timeDate == cellValue)
                     {
                         invalidData = true;
                         break;
                     }
                     if (index == dateTimeColumn)
                     {
                         Vector<string> result;
                         stringstream ss(cellValue);
                         while (ss.good())
{
                             string substr;
                             getline(ss, substr, ' ');
                             result.Add(substr);
                         }
                         windLog.setDate(result.At(0));
                         windLog.setTime(result.At(1));
                     }
                     if (index == speedColumn)
                     {
                         windLog.setSpeed(stof(cellValue));
                     }
                     if (index == solarRadColumn)
                     {
                         windLog.setSolarRad(stof(cellValue));
                     }
                     if (index == temperatureColumn)
                     {
                         windLog.setAmbientAirTemp(stof(cellValue));
                     }
                 }
                 index++;
             }
             if (!invalidData && headerTaken == true)
             {
                 dataMap[windLog.getDate()].Add(windLog);
                 bst.insert(windLog.getDate());
             }
             headerTaken = true;
         }
     }
     inFile.close();
     cout << fileName << " successfully loaded!" << endl;
     return true;
 }
References Vector< T >::Add(), Vector< T >::At(), WindRecType::getDate(), WindRecType::setAmbientAirTemp(), WindRecType::setDate(), WindRecType::setSolarRad(), WindRecType::setSpeed(), and WindRecType::setTime().
Referenced by readFiles().
reset()
void WindLogData::reset () private
Resets all static member variables to their default states.
Definition at line 456 of file WINDLOGDATA.CPP.
 {
     mode = SPEED;
     totalValue = 0;
     averageValue = 0;
     totalCount = 0;
     targetYear = 0;
     targetMonth = 0;
 }
setMode()
void WindLogData::setMode (Mode newMode) inline
Setter method for the operating mode.
Parameters
newMode - new operating mode to be set.
Definition at line 57 of file WINDLOGDATA.H.
     {
         mode = newMode;
     };
setTargetYearMonth()
void WindLogData::setTargetYearMonth (int year, int month) private
Sets the target year and month for which data is to be processed.
Parameters
year - target year to be specified. month - target month to be specified.
Definition at line 450 of file WINDLOGDATA.CPP.
 {
     targetYear = year;
     targetMonth = month;
 }
sPCC()
void WindLogData::sPCC (string month)
Calculates and prints the Solar panel correlation coefficient for a specified month.
Parameters
month - month to be specified.
Definition at line 174 of file WINDLOGDATA.CPP.
 {
     float averageSpeed = getAverageSpeed("-1", month);
     float standardDeviationSpeed = getStandardDeviationSpeed("-1", month, averageSpeed);
     float averageTemp = getAverageTemp("-1", month);
     float standardDeviationTemp = getStandardDeviationTemp("-1", month, averageTemp);
     float averageSolarRad = getAverageSolarRad("-1", month);
     float standardDeviationSolarRad = getStandardDeviationSolarRad("-1", month, averageSolarRad);
     float DevSquaredSpeed = 0.0;
     float DevSquaredTemp = 0.0;
     float DevSquaredSolarRad = 0.0;
     float S_T = 0.0;
     float S_R = 0.0;
     float T_R = 0.0;
     for(auto& [key, windLogVect] : dataMap)
     {
         if (key.GetMonthNum() == stoi(month))
         {
             for(int i = 0; i < windLogVect.getSize(); i++)
             {
                 float devSpeed = windLogVect[i].getSpeed() - averageSpeed;
                 float devTemp = windLogVect[i].getAmbientAirTemp() - averageTemp;
                 float devSolarRad = windLogVect[i].getSolarRad() - averageSolarRad;
                 DevSquaredSpeed += devSpeed * devSpeed;
                 DevSquaredTemp += devTemp * devTemp;
                 DevSquaredSolarRad += devSolarRad * devSolarRad;
                 S_T += devSpeed * devTemp;
                 S_R += devSpeed * devSolarRad;
                 T_R += devTemp * devSolarRad;
             }
         }
     }
     S_T = S_T / sqrt(DevSquaredSpeed * DevSquaredTemp);
     S_T = isnan(S_T) ? 0 : S_T;
     S_R = S_R / sqrt(DevSquaredSpeed * DevSquaredSolarRad);
     S_R = isnan(S_R) ? 0 : S_R;
     T_R = T_R / sqrt(DevSquaredTemp * DevSquaredSolarRad);
     T_R = isnan(T_R) ? 0 : T_R;
     cout << "S_T: " << S_T << endl;
     cout << "S_R: " << S_R << endl;
     cout << "T_R: " << T_R << endl;
     cout << endl;
 }
Referenced by main().
writeToCSV()
void WindLogData::writeToCSV (string fileName, string year)
Writes wind speed, temperature, solar radiation, date and time to CSV file for a specific year.
Parameters
year - year to be specified, in string
Definition at line 134 of file WINDLOGDATA.CPP.
 {
     ofstream outFile(fileName);
     outFile << year << endl;
     int count = 0;
     for(int i = 1; i <= 12; i++)
     {
         float averageSpeed = round(getAverageSpeed(year, to_string(i))*10)/10;
         float averageTemp = round(getAverageTemp(year, to_string(i))*10)/10;
         float totalSolarRadiation = round(getTotalSolarRadiationMonth(year, to_string(i))*10)/10;
         float standardDeviationSpeed = roundf(getStandardDeviationSpeed(year, to_string(i), averageSpeed)*10.0f)/10.0f;
         float standardDeviationTemp = roundf(getStandardDeviationTemp(year, to_string(i), averageTemp)*10.0f)/10.0f;
         if(averageSpeed == 0 && averageTemp == 0 && totalSolarRadiation == 0)
         {
             count++;
             continue;
         }
         else
         {
             outFile << numToMonth(to_string(i)) << ","
                     << averageSpeed
                     << '(' << standardDeviationSpeed << ')' << ","
                     << averageTemp
                     << '(' << standardDeviationTemp << ')' << ","
                     << totalSolarRadiation
                     << endl;
         }
     }
     if(count == 12)
     {
         outFile << "No Data";
     }
     outFile.close();
 }
Referenced by main().
Member Data Documentation
averageValue
float WindLogData::averageValue static private
Definition at line 216 of file WINDLOGDATA.H.
bst
Bst<Date> WindLogData::bst private
Definition at line 214 of file WINDLOGDATA.H.
dataMap
unordered_map< Date, Vector< WindRecType > > WindLogData::dataMap static private
Definition at line 213 of file WINDLOGDATA.H.
mode
WindLogData::Mode WindLogData::mode static private
Definition at line 212 of file WINDLOGDATA.H.
targetMonth
int WindLogData::targetMonth static private
Definition at line 219 of file WINDLOGDATA.H.
targetYear
int WindLogData::targetYear static private
Definition at line 218 of file WINDLOGDATA.H.
totalCount
int WindLogData::totalCount static private
Definition at line 217 of file WINDLOGDATA.H.
totalValue
float WindLogData::totalValue static private
Definition at line 215 of file WINDLOGDATA.H.
The documentation for this class was generated from the following files:
C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 10/codeblocks/classes/WINDLOGDATA.H
C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 10/codeblocks/classes/WINDLOGDATA.CPP