Lab 10: WindRecType Class Reference
WindRecType Class Reference
Logs the data of wind speed, solar radiation, ambient temperature at a specific time and date.
#include <WINDRECTYPE.H>
Public Member Functions
WindRecType ()
WindRecType (Date &date, Time &time, float s)
Date & getDate ()
Time & getTime ()
float getSpeed () const
const float getSolarRad () const
const float getAmbientAirTemp () const
void setDate (string date)
void setTime (string time)
void setSpeed (float s)
void setSolarRad (float s)
void setAmbientAirTemp (float s)
void testOutput (ostream &os, WindRecType &W) const
Private Attributes
Date d
Time t
float speed
float solarRadiation
float ambientAirTemp
Detailed Description
Logs the data of wind speed, solar radiation, ambient temperature at a specific time and date.
Contains data of date, time, wind speed, solar radiation and ambient temperature.
Author
Noor Hidayat
Definition at line 20 of file WINDRECTYPE.H.
Constructor & Destructor Documentation
WindRecType() [1/2]
WindRecType::WindRecType ()
The WindRecType default constructor initialize the wind speed to a value of 0.
Definition at line 3 of file WINDRECTYPE.CPP.
 {
     //ctor
 }
WindRecType() [2/2]
WindRecType::WindRecType (Date & date, Time & time, float s)
WindRecType Constructor
Parameters
date The time to initialize with
time The date to initialize with
s The wind speed to initialize with
Definition at line 8 of file WINDRECTYPE.CPP.
 {
     d = date;
     t = time;
     speed = s;
 }
References d, speed, and t.
Member Function Documentation
getAmbientAirTemp()
const float WindRecType::getAmbientAirTemp () const
Get the ambient air temperature value
Definition at line 67 of file WINDRECTYPE.CPP.
 {
     return ambientAirTemp;
 }
References ambientAirTemp.
Referenced by WindLogData::getAverageBst(), and WindLogData::getStdBst().
getDate()
Date & WindRecType::getDate ()
Get the date
Definition at line 72 of file WINDRECTYPE.CPP.
 {
     return d;
 }
References d.
Referenced by operator<<(), WindLogData::readFile(), and testOutput().
getSolarRad()
const float WindRecType::getSolarRad () const
Get the Solar Radiation value
Definition at line 62 of file WINDRECTYPE.CPP.
 {
     return solarRadiation;
 }
References solarRadiation.
Referenced by WindLogData::getAverageBst(), and WindLogData::getStdBst().
getSpeed()
float WindRecType::getSpeed () const
Get the wind speed
Definition at line 82 of file WINDRECTYPE.CPP.
 {
     return speed;
 }
References speed.
Referenced by WindLogData::getAverageBst(), WindLogData::getStdBst(), operator<<(), and testOutput().
getTime()
Time & WindRecType::getTime ()
Get the time
Definition at line 77 of file WINDRECTYPE.CPP.
 {
     return t;
 }
References t.
Referenced by operator<<(), and testOutput().
setAmbientAirTemp()
void WindRecType::setAmbientAirTemp (float s)
Sets the ambient air temperature
Parameters
s Contains the value of the ambient air temperature
Definition at line 57 of file WINDRECTYPE.CPP.
 {
     ambientAirTemp = s;
 }
References ambientAirTemp.
Referenced by WindLogData::readFile().
setDate()
void WindRecType::setDate (string date)
Sets the Date
Parameters
date Contains the date string in format of dd/mm/yy
Definition at line 15 of file WINDRECTYPE.CPP.
 {
     Vector<string> result;
     stringstream ss(date);
     while (ss.good())
     {
         string substr;
         getline(ss, substr, '/');
         result.Add(substr);
     }
     d.SetDay(stoi(result.At(0)));
     d.SetMonthNum(stoi(result.At(1)));
     d.SetYear(stoi(result.At(2)));
 }
References Vector< T >::Add(), Vector< T >::At(), d, Date::SetDay(), Date::SetMonthNum(), and Date::SetYear().
Referenced by WindLogData::readFile().
setSolarRad()
void WindRecType::setSolarRad (float s)
Sets the Solar radiation value
Parameters
s Contains the value of radiation
Definition at line 52 of file WINDRECTYPE.CPP.
 {
     solarRadiation = s;
 }
References solarRadiation.
Referenced by WindLogData::readFile().
setSpeed()
void WindRecType::setSpeed (float s)
Sets the speed
Parameters
s Contains the wind speed to set to
Definition at line 47 of file WINDRECTYPE.CPP.
 {
     speed = s;
 }
References speed.
Referenced by WindLogData::readFile().
setTime()
void WindRecType::setTime (string time)
Sets the Time
Parameters
time Contains the time in the format of hh:mm
Definition at line 32 of file WINDRECTYPE.CPP.
 {
     Vector<string> result;
     stringstream ss(time);
     while (ss.good())
     {
         string substr;
         getline(ss, substr, ':');
         result.Add(substr);
     }
     t.setHour(stoi(result.At(0)));
     t.setMinute(stoi(result.At(1)));
 }
References Vector< T >::Add(), Vector< T >::At(), Time::setHour(), Time::setMinute(), and t.
Referenced by WindLogData::readFile().
testOutput()
void WindRecType::testOutput (ostream & os, WindRecType & W) const
Definition at line 87 of file WINDRECTYPE.CPP.
{
     os << W.getDate().GetDay() << "/" << W.getDate().GetMonthNum() << "/" << W.getDate().GetYear() << "," << W.getTime() << "," << W.getSpeed() << "\n";
 }
References getDate(), Date::GetDay(), Date::GetMonthNum(), getSpeed(), getTime(), and Date::GetYear().
Member Data Documentation
ambientAirTemp
float WindRecType::ambientAirTemp private
Stores the Ambient Air temperature value
Definition at line 95 of file WINDRECTYPE.H.
Referenced by getAmbientAirTemp(), and setAmbientAirTemp().
d
Date WindRecType::d private
Stores the date object
Definition at line 87 of file WINDRECTYPE.H.
Referenced by getDate(), setDate(), and WindRecType().
solarRadiation
float WindRecType::solarRadiation private
Stores the solar Radiation value
Definition at line 93 of file WINDRECTYPE.H.
Referenced by getSolarRad(), and setSolarRad().
speed
float WindRecType::speed private
Stores the wind speed in float
Definition at line 91 of file WINDRECTYPE.H.
Referenced by getSpeed(), setSpeed(), and WindRecType().
t
Time WindRecType::t private
Stores the time object
Definition at line 89 of file WINDRECTYPE.H.
Referenced by getTime(), setTime(), and WindRecType().
The documentation for this class was generated from the following files:
C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 10/codeblocks/classes/WINDRECTYPE.H
C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 10/codeblocks/classes/WINDRECTYPE.CPP