Lab 10: Vector< T > Class Template Reference
Vector< T > Class Template Reference
The Vector class is a dynamic array.
#include <VECTOR.H>
Public Member Functions
Vector ()
Vector (int size)
~Vector ()
void Add (const T &element)
void Remove ()
T & At (int index)
const int getSize () const
void setSize (const int s)
void clearVect ()
bool IsEmpty ()
void sortVectAsc ()
Vector< T > & operator= (const Vector &obj)
T & operator[] (const int index)
const bool operator== (const Vector &rhs) const
void InsertAt (int index, const T &element)
void DeleteFrom (int index)
void print_contents () const
Private Attributes
vector< T > m_vector
Detailed Description
template<class T>
class Vector< T >
The Vector class is a dynamic array.
The vector is able to resize itself according to the demand
Author
Noor Hidayat
Definition at line 19 of file VECTOR.H.
Constructor & Destructor Documentation
Vector() [1/2]
template<class T > Vector< T >::Vector
The default constructor of Vector
Definition at line 122 of file VECTOR.H.
 {
     m_vector = vector<T>();
 }
Vector() [2/2]
template<class T > Vector< T >::Vector (int size)
Definition at line 128 of file VECTOR.H.
 {
     m_vector = vector<T>(size);
 }
~Vector()
template<class T > Vector< T >::~Vector
The destructor of Vector that deletes the array from the heap
Definition at line 134 of file VECTOR.H.
 {
 }
Member Function Documentation
Add()
template<class T > void Vector< T >::Add (const T & element)
Adds an element to the back of the Vector. If the Vector is full, automatically resizes bigger.
Definition at line 140 of file VECTOR.H.
 {
     m_vector.push_back(element);
 }
Referenced by WindLogData::readFile(), readFiles(), WindRecType::setDate(), and WindRecType::setTime().
At()
template<class T > T & Vector< T >::At (int index)
Returns the element at the specified index
Parameters
index The integer of the index
Definition at line 152 of file VECTOR.H.
 {
     return m_vector.at(index);
 }
Referenced by WindLogData::getAverageBst(), WindLogData::getStdBst(), WindLogData::readFile(), WindRecType::setDate(), and WindRecType::setTime().
clearVect()
template<class T > void Vector< T >::clearVect
Empties the vector
Definition at line 170 of file VECTOR.H.
 {
     m_vector.clear();
 }
DeleteFrom()
template<class T > void Vector< T >::DeleteFrom (int index)
Deletes an element at the specified index in the Vector.
Parameters
index The index at which to delete the element
Definition at line 237 of file VECTOR.H.
 {
     if (index >= 0 && index < getSize())
     {
         m_vector.erase(m_vector.begin() + index);
     }
     else
     {
         throw "Unable to delete index. Out of range";
     }
 }
getSize()
template<class T > const int Vector< T >::getSize
Get the number of elements inside the Vector
Definition at line 158 of file VECTOR.H.
 {
     return m_vector.size();
 }
Referenced by WindLogData::getAverageBst(), WindLogData::getStdBst(), and readFiles().
InsertAt()
template<class T > void Vector< T >::InsertAt (int index, const T & element)
Inserts an element at the specified index in the Vector.
Parameters
index The index at which to insert the element
element The element to insert
Definition at line 220 of file VECTOR.H.
 {
     if (index >= 0 && index <= getSize())
     {
         m_vector.insert(m_vector.begin() + index, element);
     }
     else
     {
         throw "Unable to insert at index. Out of range";
     }
 }
IsEmpty()
template<class T > bool Vector< T >::IsEmpty
Checks if the vector is empty. Returns true if empty Returns false if not empty
Definition at line 176 of file VECTOR.H.
 {
     return m_vector.empty();
 }
operator=()
template<class T > Vector< T > & Vector< T >::operator= (const Vector< T > & obj)
Operator overload for the equal sign. To create a deep copy
Parameters
obj Is the vector obj to copy
Definition at line 197 of file VECTOR.H.
 {
     if (this != &obj)
     {
         m_vector = obj.m_vector;
     }
     return *this;
 }
References Vector< T >::m_vector.
operator==()
template<class T > const bool Vector< T >::operator== (const Vector< T > & rhs) const
Operator overload for the == to check whether Vector obj has the same content
Parameters
rhs Holds the vector obj
Definition at line 214 of file VECTOR.H.
 {
     return m_vector == rhs.m_vector;
 }
References Vector< T >::m_vector.
operator[]()
template<class T > T & Vector< T >::operator[] (const int index)
Operator overload for the bracket []. To modify or get any index of the element
Definition at line 208 of file VECTOR.H.
 {
     return m_vector[index];
 }
print_contents()
template<class T > void Vector< T >::print_contents
Definition at line 252 of file VECTOR.H.
 {
     for (const auto& element : m_vector)
     {
         cout << element << ", ";
     }
     cout << endl;
 }
Remove()
template<class T > void Vector< T >::Remove
Deletes the last element of the Vector If Vector is empty, throws an error
Definition at line 146 of file VECTOR.H.
 {
     m_vector.pop_back();
 }
setSize()
template<class T > void Vector< T >::setSize (const int s)
Set the number of elements the Vector can hold
Parameters
s Is the size value to change the Vector to
Definition at line 164 of file VECTOR.H.
 {
     m_vector.resize(s);
 }
sortVectAsc()
template<class T > void Vector< T >::sortVectAsc
Sorts the array to ascending
Definition at line 182 of file VECTOR.H.
 {
     for(size_t i = 0; i < m_vector.size() - 1; ++i)
     {
         for(size_t j = 0; j < m_vector.size() - i - 1; ++j)
             if(m_vector[j] > m_vector[j + 1])
             {
                 T temp = m_vector[j];
                 m_vector[j] = m_vector[j + 1];
                 m_vector[j + 1] = temp;
             }
     }
 }
Member Data Documentation
m_vector
template<class T > vector<T> Vector< T >::m_vector private
Stores data into vector
Definition at line 116 of file VECTOR.H.
Referenced by Vector< T >::operator=(), and Vector< T >::operator==().
The documentation for this class was generated from the following file:
C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 10/codeblocks/classes/VECTOR.H