Lab 10: std::hash< Date > Struct Reference
std::hash< Date > Struct Reference
#include <DATE.H>
Public Member Functions
size_t operator() (const Date &k) const
Detailed Description
Definition at line 124 of file DATE.H.
Member Function Documentation
operator()()
size_t std::hash< Date >::operator() (const Date & k) const inline
Definition at line 125 of file DATE.H.
{
             size_t h1 = hash<int>()(k.GetDay());
             size_t h2 = hash<int>()(k.GetMonthNum());
             size_t h3 = hash<int>()(k.GetYear());
             return h1 ^ (h2 << 1) ^ (h3 << 2);
         }
References Date::GetDay(), Date::GetMonthNum(), and Date::GetYear().
The documentation for this struct was generated from the following file:
C:/Users/Veebee/Desktop/ICT283_COPY/0. Remodule/Labs/Lab 10/codeblocks/classes/DATE.H