//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : B.h
//  @ Date : 17/03/2022
//  @ Author : smr
//
//


#if !defined(_B_H)
#define _B_H

#include "A.h"

#include<iostream>  // added manually in code. If you regenerate code from UML, all this
                    // will be overwritten

using namespace std; // deliberately opening the entire std namespace

class B : public A {
public:
	B();
	~B();
	int getD();
	void setD(int i = 0);
	void setName(char* nam);
	const char* getAddress();
	bool validate();
	B& operator++();
	B& operator+(const B& r);
	friend ostream & operator<<(ostream &os, const B& bb);  // friend to be added manually in code
private:
	int d;
	char e;
	char name;  // needs to be changed to char name[10] manually
	char* address;
};

#endif  //_B_H
