//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : A.h
//  @ Date : 17/03/2022
//  @ Author : smr
//
//


#if !defined(_A_H)
#define _A_H


// Thiis is the test for A.
class A {
public:
	void get();
	void set();
protected:
	float b;
	bool validate();
private:
	int a;
};

#endif  //_A_H
